# Generated by Django 6.0.5 on 2026-07-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dept_code', models.CharField(help_text='e.g., CS', max_length=20)),
                ('listing_type', models.CharField(choices=[('OFFER', 'Offering (Lending/Selling)'), ('SEEK', 'Seeking (Borrowing/Buying)')], default='OFFER', max_length=5)),
                ('condition', models.CharField(choices=[('NEW', 'Like New'), ('GOOD', 'Good'), ('USED', 'Fair / Heavily Used')], default='GOOD', max_length=4)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
